In [1]:
import pandas as pd

In [18]:
df1 = pd.read_csv("spotify_millsongdata.csv")
df2 = pd.read_csv("tcc_ceds_music.csv")

In [19]:
df1.head()

,artist,song,link,text
0,ABBA,Ahe's My Kind Of Girl,/a/abba/ahes+my+kind+of+girl_20598417.html,"Look at her face, it's a wonderful face \r\nA..."
1,ABBA,"Andante, Andante",/a/abba/andante+andante_20002708.html,"Take it easy with me, please \r\nTouch me gen..."
2,ABBA,As Good As New,/a/abba/as+good+as+new_20003033.html,I'll never know why I had to go \r\nWhy I had...
3,ABBA,Bang,/a/abba/bang_20598415.html,Making somebody happy is a question of give an...
4,ABBA,Bang-A-Boomerang,/a/abba/bang+a+boomerang_20002668.html,Making somebody happy is a question of give an...

In [3]:
df2.head()

,Unnamed: 0,artist_name,track_name,release_date,genre,lyrics,len,dating,violence,world/life,...,sadness,feelings,danceability,loudness,acousticness,instrumentalness,valence,energy,topic,age
0,0,mukesh,mohabbat bhi jhoothi,1950,pop,hold time feel break feel untrue convince spea...,95,0.000598,0.063746,0.000598,...,0.380299,0.117175,0.357739,0.454119,0.997992,0.901822,0.339448,0.137110,sadness,1.0
1,4,frankie laine,i believe,1950,pop,believe drop rain fall grow believe darkest ni...,51,0.035537,0.096777,0.443435,...,0.001284,0.001284,0.331745,0.647540,0.954819,0.000002,0.325021,0.263240,world/life,1.0
2,6,johnnie ray,cry,1950,pop,sweetheart send letter goodbye secret feel bet...,24,0.002770,0.002770,0.002770,...,0.002770,0.225422,0.456298,0.585288,0.840361,0.000000,0.351814,0.139112,music,1.0
3,10,pérez prado,patricia,1950,pop,kiss lips want stroll charm mambo chacha merin...,54,0.048249,0.001548,0.001548,...,0.225889,0.001548,0.686992,0.744404,0.083935,0.199393,0.775350,0.743736,romantic,1.0
4,12,giorgos papadopoulos,apopse eida oneiro,1950,pop,till darling till matter know till dream live ...,48,0.001350,0.001350,0.417772,...,0.068800,0.001350,0.291671,0.646489,0.975904,0.000246,0.597073,0.394375,romantic,1.0

In [6]:
dic = {df2.artist_name[n]:df2.genre[n] for n in range(len(df2))}

In [34]:
df1["artist"] = df1["artist"].str.lower()
df1['genre'] = df1['artist'].map(dic)
df1.dropna(subset=['genre'], inplace=True)
df1.drop('link', axis=1, inplace=True)

In [35]:
df1

,artist,track_name,lyrics,genre
0,abba,Ahe's My Kind Of Girl,"Look at her face, it's a wonderful face \r\nA...",pop
1,abba,"Andante, Andante","Take it easy with me, please \r\nTouch me gen...",pop
2,abba,As Good As New,I'll never know why I had to go \r\nWhy I had...,pop
3,abba,Bang,Making somebody happy is a question of give an...,pop
4,abba,Bang-A-Boomerang,Making somebody happy is a question of give an...,pop
...,...,...,...,...
57642,ziggy marley,Friend,[Chorus] \r\nI wanna thank you for the things...,reggae
57643,ziggy marley,G7,Seven richest countries in the world \r\nThem...,reggae
57644,ziggy marley,Generation,Many generation have passed away \r\nFighting...,reggae
57645,ziggy marley,Good Old Days,Irie days come on play \r\nLet the angels fly...,reggae
57646,ziggy marley,Hand To Mouth,Power to the workers \r\nMore power \r\nPowe...,reggae

In [36]:
df1.rename(columns={"song": "track_name"}, inplace=True)
df1.rename(columns={"text": "lyrics"}, inplace=True)

In [37]:
df1

,artist,track_name,lyrics,genre
0,abba,Ahe's My Kind Of Girl,"Look at her face, it's a wonderful face \r\nA...",pop
1,abba,"Andante, Andante","Take it easy with me, please \r\nTouch me gen...",pop
2,abba,As Good As New,I'll never know why I had to go \r\nWhy I had...,pop
3,abba,Bang,Making somebody happy is a question of give an...,pop
4,abba,Bang-A-Boomerang,Making somebody happy is a question of give an...,pop
...,...,...,...,...
57642,ziggy marley,Friend,[Chorus] \r\nI wanna thank you for the things...,reggae
57643,ziggy marley,G7,Seven richest countries in the world \r\nThem...,reggae
57644,ziggy marley,Generation,Many generation have passed away \r\nFighting...,reggae
57645,ziggy marley,Good Old Days,Irie days come on play \r\nLet the angels fly...,reggae
57646,ziggy marley,Hand To Mouth,Power to the workers \r\nMore power \r\nPowe...,reggae

In [39]:
df1.to_csv('dataset_atualizado.csv', index=False)